### ISSUE TITLE
Upload Page

### ISSUE THREAD

**Issue by Ian321** [StreamElements/issues#6]
- [x] Can't upload files. (staging)
- [x] Check file server sided again!
- [x] Add <code>accept="audio/\*,image/\*,video/webm"</code> to the file input.
 the explorer/file browser.
- [x] Change height and position of the error.

**Comment by Darko** [comment]
`ngf-pattern="'audio/*,image/*,video/webm'"`
This takes care of uploading files. It makes sure it's audio, image or vide/webm.

**Comment by Darko** [comment]
There is ngf-accept, it's from library for file uploading called ng-file-upload
`ngf-accept="'audio/*,image/*,video/webm'"`

**Comment by styler** [comment]
# Fixed 
<img src="http://i3.kym-cdn.com/photos/images/facebook/001/037/049/75d.png"/>
